### ISSUE TITLE
404 errors when plex season doesn't have a poster

### ISSUE THREAD

**Issue by dude22072** [chrisbenincasa/tunarr#1002]
With Plex, a season may not always have a specific poster for it, instead displaying the poster for the parent series in the Plex UI. Tunarr has issues with this and will log an error, as trying to get the `/thumb` for these will return a 404 as it doesn't exist. Looking at the XML for one of these seasons, the `<Image>` tag contains the ID of their parent node rather than themselves, but Tunarr seems to ignore this and always use the ID of the item, causing the 404.

**Comment by chrisbenincasa** [comment]
The issue here is displaying the broken image in the grid view program selector ui?

**Comment by dude22072** [comment]
Yes, broken image in tunarr's grid view as well as a chonky error in the tunarr log:
```
2024-12-05T19:48:15.793Z [error]: undefined {"url":"/api/metadata/external"}
    error: {
      "message": "Request failed with status code 404",
      "name": "AxiosError",
      "stack":
          AxiosError: Request failed with status code 404
              at settle (file:///tunarr/server/build/bundle.js:166067:13)
              at RedirectableRequest.handleResponse (file:///tunarr/server/build/bundle.js:166922:9)
              at RedirectableRequest.emit (node:events:518:28)
              at RedirectableRequest._processResponse (file:///tunarr/server/build/bundle.js:101561:14)
              at RedirectableRequest._onNativeResponse (file:///tunarr/server/build/bundle.js:101348:15)
              at Object.onceWrapper (node:events:633:26)
              at ClientRequest.emit (node:events:518:28)
              at HTTPParser.parserOnIncomingClient (node:_http_client:702:27)
              at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17)
              at TLSSocket.socketOnData (node:_http_client:544:22)
              at TLSSocket.emit (node:events:518:28)
              at addChunk (node:internal/streams/readable:561:12)
              at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
              at Readable.push (node:internal/streams/readable:392:5)
              at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)
              at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "User-Agent": "axios/1.6.0",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "url": "https://REDACTED.plex.direct:32400/library/metadata/34499/thumb?X-Plex-Token=REDACTED",
        "responseType": "stream",
        "method": "get"
      },
      "code": "ERR_BAD_REQUEST",
      "status": 404
    }
```
