### ISSUE TITLE
Can't save 'Channel Edit Form' - 500

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#284]
When editing a channel (currently I just testing changing the channel name) I get a 500 and nothing saves

<img width="1463" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/d525bbfc-1f6a-4017-9bea-f7d93e1bada0">

**Comment by chrisbenincasa** [comment]
Anything in the server log?

**Comment by chrisbenincasa** [comment]
I got one:

```
@tunarr/server:dev: 2024-04-13T13:28:29.425Z [error] api/channelsApi.ts : /api/channels/:id Trying to set Channel.fillerRepeatCooldown of type 'number' to l { '$d': { milliseconds: 30000 }, '$l': 'en', '$ms': 30000 } of type 'object' undefined
@tunarr/server:dev:     ValidationError: Trying to set Channel.fillerRepeatCooldown of type 'number' to l { '$d': { milliseconds: 30000 }, '$l': 'en', '$ms': 30000 } of type 'object'
@tunarr/server:dev:         at ValidationError.fromWrongPropertyType (/Users/christianbenincasa/Code/projects/tunarr/node_modules/.pnpm/@mikro-orm+core@6.2.0/node_modules/@mikro-orm/core/errors.js:23:16)
@tunarr/server:dev:         at EntityValidator.validateProperty (/Users/christianbenincasa/Code/projects/tunarr/node_modules/.pnpm/@mikro-orm+core@6.2.0/node_modules/@mikro-orm/core/entity/EntityValidator.js:74:48)
@tunarr/server:dev:         at EntityAssigner.assignProperty (/Users/christianbenincasa/Code/projects/tunarr/node_modules/.pnpm/@mikro-orm+core@6.2.0/node_modules/@mikro-orm/core/entity/EntityAssigner.js:91:50)
@tunarr/server:dev:         at /Users/christianbenincasa/Code/projects/tunarr/node_modules/.pnpm/@mikro-orm+core@6.2.0/node_modules/@mikro-orm/core/entity/EntityAssigner.js:31:35
@tunarr/server:dev:         at Array.forEach (<anonymous>)
@tunarr/server:dev:         at EntityAssigner.assign (/Users/christianbenincasa/Code/projects/tunarr/node_modules/.pnpm/@mikro-orm+core@6.2.0/node_modules/@mikro-orm/core/entity/EntityAssigner.js:30:27)
@tunarr/server:dev:         at Channel.assign (/Users/christianbenincasa/Code/projects/tunarr/node_modules/.pnpm/@mikro-orm+core@6.2.0/node_modules/@mikro-orm/core/entity/BaseEntity.js:34:48)
@tunarr/server:dev:         at ChannelDB.updateChannel (/Users/christianbenincasa/Code/projects/tunarr/server/src/dao/channelDb.ts:194:19)
@tunarr/server:dev:         at Object.<anonymous> (/Users/christianbenincasa/Code/projects/tunarr/server/src/api/channelsApi.ts:148:64)
@tunarr/server:dev:         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by chrisbenincasa** [comment]
Looks like we're trying to pass the dayjs duration object directly

**Comment by markdavella** [comment]
Ah good find, I can fix this one up soonish

**Comment by chrisbenincasa** [comment]
I think it's happening on the backend but i'm not sure why yet

**Comment by chrisbenincasa** [comment]
I wonder if this started when i updated mikro orm yesterday

**Comment by chrisbenincasa** [comment]
Def a backend thing. I think I have a fix
