### ISSUE TITLE
Save "first run" and "migration state" in canonical location

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#474]
We currently base whether a legacy migration should be run based on whether we have to create the Tunarr database directory. This assumption falls apart in scenarios where the DB directory is a path bound to container from a host, which necessarily must exist to run the container. 

Instead, we should use a setting to determine whether a migration should be run. This flag actually already exists in the settings.json, but we should reevaluate whether we want it there or in the SQLite DB itself. And furthermore, we may want a more general blob to store other types of state ... so the settings.json flag could change shape. 

We should be careful to choose an indicator that won't accidentally overwrite Tunarr settings on subsequent runs. 

An alternative approach would be to make the legacy import explicit. This option is supported today with the "force" flag but it's not as "smart" and seamless as I'd like the UX to be.

**Comment by chrisbenincasa** [comment]
More details in #434

**Comment by chrisbenincasa** [comment]
This might be simpler than I thought, looking into whether I can just remove the `!hasTunarrDb` bit here:

https://github.com/chrisbenincasa/tunarr/blob/main/server/src/server.ts#L72

**Comment by josway** [comment]
Migration is kicking off now but Error-ing out looking for a directory that doesn't exist "channel-lineups" I believe this is just "channels" in Unraid. 

2024-06-04T13:00:15.615Z [info]: Searching for legacy dizquetv directory at /.dizquetv
2024-06-04T13:00:15.620Z [info]: A legacy .dizquetv database was located.
2024-06-04T13:00:15.621Z [info]: Migrating from legacy database folder...
2024-06-04T13:00:15.870Z [error]: Unable to migrate channels 
    err: {
      "type": "Error",
      "message": "ENOENT: no such file or directory, mkdir '/.dizquetv/channel-lineups'",
      "stack":
          Error: ENOENT: no such file or directory, mkdir '/.dizquetv/channel-lineups'
              at async Object.mkdir (node:internal/fs/promises:855:10)
              at async createDirectoryIfNotExists (file:///tunarr/server/build/bundle.js:257742:5)
              at async LegacyChannelMigrator.migrateChannels (file:///tunarr/server/build/bundle.js:269721:5)
              at async LegacyDbMigrator.migrateFromLegacyDbInner (file:///tunarr/server/build/bundle.js:270596:9)
              at async withDb (file:///tunarr/server/build/bundle.js:262860:12)
              at async initServer (file:///tunarr/server/build/bundle.js:277052:5)
              at async Object.handler (file:///tunarr/server/build/bundle.js:277347:5)
      "errno": -2,
      "code": "ENOENT",
      "syscall": "mkdir",
      "path": "/.dizquetv/channel-lineups"
    }

**Comment by chrisbenincasa** [comment]
channel-lineups is a Tunarr concept. It looks like it's failing trying to create the Tunarr directory within the dizquetv directory. Are the mappings right?

**Comment by chrisbenincasa** [comment]
Oh I see - there is a minor bug in the legacy migrator. Just a minute.

**Comment by chrisbenincasa** [comment]
Ok, should be fixed in fb49e4ebd6557c5c0c49a2eabf3e70d282099731. I will kick another release.
