### ISSUE TITLE
[Bug]: Connect Plex Loops After SSO

### ISSUE THREAD

**Issue by ThisGuyNeedsABeer** [chrisbenincasa/tunarr#598]
### Contact Details

Via GitHub Please

### What happened?

Attempting to connect Plex, I get through the SSO stage, and Plex never links. Using the latest Docker build running via Unraid. My Plex instance and Tunarr are on the same VLAN, Plex is accessible from the web and locally. 

Tried 3 browsers, Chrome, Edge, FireFox. I got a "New login to your plex account" alert, but the server does not appear in the list.

Happy to provide any logs that may assist.

### Version

https://github.com/chrisbenincasa/tunarr/pkgs/container/tunarr (latest)

### What browser did you experience the the problem on?

Chrome (125.0.6422.142 (Official Build) (64-bit)), FF (127.0.2 (64-bit)), and MS Edge

### What operating system are you using?

Windows 11 / macOS Sonoma 14.5

### Relevant log output

```shell
No logs, just a loop
```

**Comment by chrisbenincasa** [comment]
Thanks for the report. Can you see if there is anything in the browser
console logs?

**Comment by ThisGuyNeedsABeer** [comment]
```
        "env": {},
        "headers": {
          "Accept": "application/json",
          "X-Plex-Device": "Tunarr",
          "X-Plex-Device-Name": "Tunarr",
          "X-Plex-Product": "Tunarr",
          "X-Plex-Version": "0.1",
          "X-Plex-Client-Identifier": "[REDACTED]",
          "X-Plex-Platform": "Chrome",
          "X-Plex-Platform-Version": "80.0",
          "X-Plex-Token": "[REDCATED]",
          "User-Agent": "axios/1.6.0",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
**** NOT MY IP OR EVEN CLOSE ****
        "baseURL": "https://192-168-0-125.c20c3fbb7bde427290757d0a83d3d488.plex.direct:32400",
        "method": "get",
        "url": "/",
        "metadata": {
          "startTime": 1719644729321
        }
      },
      "code": "ETIMEDOUT",
      "status": null
    }
**** NOT MY IP OR EVEN CLOSE ****
2024-06-29T07:08:40.605Z [error]: Plex request error: connect ETIMEDOUT 172.31.200.1:32400 
    err: {
      "message": "connect ETIMEDOUT 172.31.200.1:32400: connect ETIMEDOUT 172.31.200.1:32400",
      "name": "Error",
      "stack":
          Error: connect ETIMEDOUT 172.31.200.1:32400
              at AxiosError.from (file:///tunarr/server/build/bundle.js:241576:14)
              at RedirectableRequest.handleRequestError (file:///tunarr/server/build/bundle.js:243323:34)
              at RedirectableRequest.emit (node:events:519:28)
              at eventHandlers.<computed> (file:///tunarr/server/build/bundle.js:121942:28)
              at ClientRequest.emit (node:events:519:28)
              at TLSSocket.socketErrorListener (node:_http_client:500:9)
              at TLSSocket.emit (node:events:519:28)
              at emitErrorNT (node:internal/streams/destroy:169:8)
              at emitErrorCloseNT (node:internal/streams/destroy:128:3)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
          caused by: Error: connect ETIMEDOUT 172.31.200.1:32400
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
              at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json",
          "X-Plex-Device": "Tunarr",
          "X-Plex-Device-Name": "Tunarr",
          "X-Plex-Product": "Tunarr",
          "X-Plex-Version": "0.1",
          "X-Plex-Client-Identifier": "[REDACTED]",
          "X-Plex-Platform": "Chrome",
          "X-Plex-Platform-Version": "80.0",
          "X-Plex-Token": "[REDACTED]",
          "User-Agent": "axios/1.6.0",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "baseURL": "https://172-31-200-1.c20c3fbb7bde427290757d0a83d3d488.plex.direct:32400",
        "method": "get",
        "url": "/",
        "metadata": {
          "startTime": 1719644789327
        }
      },
      "code": "ETIMEDOUT",
      "status": null
    }
2024-06-29T08:00:04.386Z [info]: XMLTV Updated at 6/29/2024, 4:00:03 AM {"task":"update-xmltv"}
2024-06-29T12:00:00.304Z [info]: XMLTV Updated at 6/29/2024, 8:00:00 AM {"task":"update-xmltv"}

 _____ _   _ _  _   _   ___ ___ 
|_   _| | | | \| | /_\ | _ \ _ \
  | | | |_| | .` |/ _ \|   /   /
  |_|  \___/|_|\_/_/ \_\_|_\_|_\

                0.1.0

2024-06-29T15:43:24.423Z [info]: Searching for legacy dizquetv directory at /.dizquetv
/tunarr/server/build/.tunarr/stream-cache.json null
2024-06-29T15:43:25.781Z [info]: XMLTV Updated at 6/29/2024, 11:43:25 AM {"task":"update-xmltv"}
2024-06-29T15:43:25.812Z [info]: HTTP server running on port: http://0.0.0.0:8000
2024-06-29T15:43:32.627Z [info]: Open event channel.
2024-06-29T15:44:29.939Z [info]: Open event channel.

```

**Comment by Momar8989** [comment]
I'm having the same issue.  Just installed new on Unraid.  Click, connect to plex, sign in, then the window closes.  Return to Tunarr and it still says "Connect to Plex".  Tried a few times all on chrome.

**Comment by ThisGuyNeedsABeer** [comment]
Watching my logs, it's showing Tunarr trying to connect to varions LAN IP addresses outside of my subnet with claim tokens in plaintext.

**Comment by chrisbenincasa** [comment]
I can look into this more next week, I'm away right now. 

Tunarr hits the Plex "devices" endpoint after authenticating and attempts to find successful connections for any device that has the "server" capability.

**Comment by chrisbenincasa** [comment]
The code is here: https://github.com/chrisbenincasa/tunarr/blob/dev/web/src/helpers/plexLogin.ts

All of these connections should be using HTTPS so the token exchange in plaintext should not be a worry

**Comment by chrisbenincasa** [comment]
This may be helpful to do on your end: https://support.plex.tv/articles/206721658-using-plex-tv-resources-information-to-troubleshoot-app-connections/

The `/resources` path is what Tunarr hits after successful token exchange in order to find a list of possible servers to add. Based on your server log, it does look like token exchange with Plex is happening successfully and you are making it to the "ping and check status" phase of the login process. 

The IPs outside of your subnet are appearing on that plex.tv `/resources` API endpoint for some reason. 

The other thing we need to figure out is why this ends in failure. My best guess right now is that none of the attempted connections are working for Tunarr, so we the part where we actually _add_ the server [here](https://github.com/chrisbenincasa/tunarr/blob/35e4f04bc435f9fa303842ee4057bc771317b656/web/src/components/settings/AddPlexServer.tsx#L33) never happens (`connections` is empty).

**Comment by chrisbenincasa** [comment]
https://github.com/chrisbenincasa/tunarr/pull/607 adds some more logging about which servers were tried.

You can cross-reference against the `https://plex.tv/api/v2/resources?includeHttps=1&X-Plex-Token=XYZ&X-Client-Identifier=tunarr`  endpoint to see if everything looks legit. Tunarr will only attempt to contact "resource" entries that have a "provides" value that include "server".

**Comment by finalFlick** [comment]
Same issue need any info?

**Comment by chrisbenincasa** [comment]
If this is still an issue for you, you can try manually adding you Plex server details now that https://github.com/chrisbenincasa/tunarr/pull/622 is released (edge and 0.3.1)

**Comment by jmoseley** [comment]
I am experiencing this same issue. I think the extra plex servers in the `/resources` call are server that have been shared with me (I have friends that have plex, and they have given me access to stream from their servers).

Ideally I would be able to add their servers as media sources as well.

**Comment by chrisbenincasa** [comment]
@jmoseley extra logging for failed auto-connections with Plex was added in https://github.com/chrisbenincasa/tunarr/commit/3f92f16fb02166239bc33b0f9b4ca5727b3be52b

These should appear in your browser's console log. Additionally, there are likely logs on the server side, since the connection is attempted through the server. Let me know if you are able to provide any of these logs for further context so we can diagnose the issue further.

**Comment by chrisbenincasa** [comment]
Closing this out as stale - please LMK if this is still an issue for you and if the extra logging I added provides an extra context here.

**Comment by dmd** [comment]
I've been looking in on Tunarr every few months for the last year and every time bounce off because Plex login doesn't work. Does it work for *anyone* or is this just not something Tunarr can do?

**Comment by chrisbenincasa** [comment]
@dmd I know many have used this to success, including me every time I set up a new instance for testing. In any case, there is always the manual login fallback if the auto connect does not work for you. 

Auto connect failures will show themselves in the logs. It's generally because of a network misconfiguration and tunarr is unable to communicate with the URL that plex connect giving. You can see what plex URL you are receiving by looking at https://plex.tv/devices.xml.
