### ISSUE TITLE
[Bug]: Error saving programs. Zodios: Invalid Body parameter 'body'

### ISSUE THREAD

**Issue by BootlegSamurai** [chrisbenincasa/tunarr#604]
### What happened?

I am getting the "Error saving programs. Zodios: Invalid Body parameter 'body'" error when trying to add about 20 shows to a new channel and save. 

### Version

0.1.0

### What browser did you experience the the problem on?

Firefox 127.0.1

### What operating system are you using?

Unraid 6.12.4 

### Relevant log output

```shell
"baseURL": "https://172-18-0-1.840ea31f07404fb6a3e68e681ac622e8.plex.direct:32400",
        "method": "get",
        "url": "/library/metadata/7343",
        "metadata": {
          "startTime": 1720133125320
        }
      },
      "code": "ECONNRESET",
      "status": null
    }
2024-07-04T22:45:25.325Z [error]: Error querying Plex for item 7343
2024-07-04T22:45:25.335Z [error]: Plex request error: socket hang up 
    err: {
      "message": "socket hang up: socket hang up",
      "name": "Error",
      "stack":
          Error: socket hang up
              at AxiosError.from (file:///tunarr/server/build/bundle.js:241576:14)
              at RedirectableRequest.handleRequestError (file:///tunarr/server/build/bundle.js:243323:34)
              at RedirectableRequest.emit (node:events:519:28)
              at eventHandlers.<computed> (file:///tunarr/server/build/bundle.js:121942:28)
              at ClientRequest.emit (node:events:519:28)
              at TLSSocket.socketCloseListener (node:_http_client:473:11)
              at TLSSocket.emit (node:events:531:35)
              at node:net:338:12
              at TCP.done (node:_tls_wrap:657:7)
              at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
          caused by: Error: socket hang up
              at TLSSocket.socketCloseListener (node:_http_client:473:25)
              at TLSSocket.emit (node:events:531:35)
              at node:net:338:12
              at TCP.done (node:_tls_wrap:657:7)
              at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json",
          "X-Plex-Device": "Tunarr",
          "X-Plex-Device-Name": "Tunarr",
          "X-Plex-Product": "Tunarr",
          "X-Plex-Version": "0.1",
          "X-Plex-Client-Identifier": "p86cy1w47clco3ro8t92nfy1",
          "X-Plex-Platform": "Chrome",
          "X-Plex-Platform-Version": "80.0",
          "X-Plex-Token": "5A_uyd3Vb-QT6jjBFdbD",
          "User-Agent": "axios/1.6.0",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "baseURL": "https://172-18-0-1.840ea31f07404fb6a3e68e681ac622e8.plex.direct:32400",
        "method": "get",
        "url": "/library/metadata/3888",
        "metadata": {
          "startTime": 1720133125331
        }
      },
      "code": "ECONNRESET",
      "status": null
    }
2024-07-04T22:45:25.336Z [error]: Error querying Plex for item 3888
2024-07-04T22:45:25.504Z [info]: XMLTV Updated at 7/4/2024, 6:45:25 PM {"task":"update-xmltv"}
2024-07-04T22:49:12.801Z [info]: Remove event channel.
2024-07-04T22:49:12.979Z [info]: XMLTV Updated at 7/4/2024, 6:49:12 PM {"task":"update-xmltv"}
2024-07-04T22:49:13.428Z [info]: Open event channel.
/tunarr/server/build/.tunarr/channel-lineups/5f629c86-3d25-48fe-9d55-3fe47e4f2ba2.json null
2024-07-04T22:49:31.022Z [info]: XMLTV Updated at 7/4/2024, 6:49:31 PM {"task":"update-xmltv"}
2024-07-04T22:55:43.250Z [info]: XMLTV Updated at 7/4/2024, 6:55:43 PM {"task":"update-xmltv"}
/tunarr/server/build/.tunarr/channel-lineups/e79aa007-572f-455e-bf69-e82a641b4f41.json null
2024-07-04T22:56:29.815Z [info]: XMLTV Updated at 7/4/2024, 6:56:29 PM {"task":"update-xmltv"}
2024-07-04T22:57:06.531Z [info]: Remove event channel.
2024-07-04T22:57:07.471Z [info]: Open event channel.
```

**Comment by BootlegSamurai** [comment]
Think I got this figured out. I am working on this remotely and I think the Plex connection was acting weird. I built a vm and it started working after editing my plex url to use the local IP instead of the external.

**Comment by chrisbenincasa** [comment]
Nice, glad to hear you got it working!
