### ISSUE TITLE
[Bug] Select all filler shows query error - ambiguous column

### ISSUE THREAD

**Issue by mejacobarussell** [chrisbenincasa/tunarr#634]
### Contact Details

mrjacobarussell@gmail.com

### What happened?

I click on "flex" and get error 
Oops!
Looks like something went wrong.
6e@http://192.168.0.8:8888/web/assets/index-52391a51.js:323:1058
p@http://192.168.0.8:8888/web/assets/index-52391a51.js:323:4361

logs show 

2024-07-24T13:20:34.646Z [error]: /api/filler-lists 
    err: {
      "type": "SqliteError",
      "message": "ambiguous column name: program_uuid",
      "stack":
          SqliteError: ambiguous column name: program_uuid
              at Database.prepare (file:///tunarr/server/build/bundle.js:24711:26)
              at SqliteConnection.executeQuery (file:///tunarr/server/build/bundle.js:260844:27)
              at connection.executeQuery (file:///tunarr/server/build/bundle.js:258745:35)
              at file:///tunarr/server/build/bundle.js:253323:40
              at DefaultConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:258597:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async _DefaultQueryExecutor.executeQuery (file:///tunarr/server/build/bundle.js:253322:12)
              at async _SelectQueryBuilderImpl.execute (file:///tunarr/server/build/bundle.js:254762:21)
              at async FillerDB.getAllFillers (file:///tunarr/server/build/bundle.js:267024:12)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:272896:23)
      "code": "SQLITE_ERROR"
    }
2024-07-24T13:20:34.647Z [error]: undefined {"url":"/api/filler-lists"}
    error: {
      "code": "SQLITE_ERROR"
    }

### Version

0.2.0

### What browser did you experience the the problem on?

Safari (17.5)

### What operating system are you using?

macOS (10.15.7)

### Relevant log output

```shell
text  error  warn  system  array  login  

            "Metadata",
            0,
            "contentRating"
          ],
          "message": "Required"
        }
      ],
      "name": "ZodError"
    }
2024-07-24T13:20:27.757Z [error] <>: Error requesting item rom Plex: 'parse_error' <no message>
2024-07-24T13:20:31.067Z [error]: Query error 
    err: {
      "type": "SqliteError",
      "message": "ambiguous column name: program_uuid",
      "stack":
          SqliteError: ambiguous column name: program_uuid
              at Database.prepare (file:///tunarr/server/build/bundle.js:24711:26)
              at SqliteConnection.executeQuery (file:///tunarr/server/build/bundle.js:260844:27)
              at connection.executeQuery (file:///tunarr/server/build/bundle.js:258745:35)
              at file:///tunarr/server/build/bundle.js:253323:40
              at DefaultConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:258597:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async _DefaultQueryExecutor.executeQuery (file:///tunarr/server/build/bundle.js:253322:12)
              at async _SelectQueryBuilderImpl.execute (file:///tunarr/server/build/bundle.js:254762:21)
              at async FillerDB.getAllFillers (file:///tunarr/server/build/bundle.js:267024:12)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:272896:23)
      "code": "SQLITE_ERROR"
    }
2024-07-24T13:20:31.067Z [error]: /api/filler-lists 
    err: {
      "type": "SqliteError",
      "message": "ambiguous column name: program_uuid",
      "stack":
          SqliteError: ambiguous column name: program_uuid
              at Database.prepare (file:///tunarr/server/build/bundle.js:24711:26)
              at SqliteConnection.executeQuery (file:///tunarr/server/build/bundle.js:260844:27)
              at connection.executeQuery (file:///tunarr/server/build/bundle.js:258745:35)
              at file:///tunarr/server/build/bundle.js:253323:40
              at DefaultConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:258597:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async _DefaultQueryExecutor.executeQuery (file:///tunarr/server/build/bundle.js:253322:12)
              at async _SelectQueryBuilderImpl.execute (file:///tunarr/server/build/bundle.js:254762:21)
              at async FillerDB.getAllFillers (file:///tunarr/server/build/bundle.js:267024:12)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:272896:23)
      "code": "SQLITE_ERROR"
    }
2024-07-24T13:20:31.067Z [error]: undefined {"url":"/api/filler-lists"}
    error: {
      "code": "SQLITE_ERROR"
    }
2024-07-24T13:20:34.646Z [error]: Query error 
    err: {
      "type": "SqliteError",
      "message": "ambiguous column name: program_uuid",
      "stack":
          SqliteError: ambiguous column name: program_uuid
              at Database.prepare (file:///tunarr/server/build/bundle.js:24711:26)
              at SqliteConnection.executeQuery (file:///tunarr/server/build/bundle.js:260844:27)
              at connection.executeQuery (file:///tunarr/server/build/bundle.js:258745:35)
              at file:///tunarr/server/build/bundle.js:253323:40
              at DefaultConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:258597:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async _DefaultQueryExecutor.executeQuery (file:///tunarr/server/build/bundle.js:253322:12)
              at async _SelectQueryBuilderImpl.execute (file:///tunarr/server/build/bundle.js:254762:21)
              at async FillerDB.getAllFillers (file:///tunarr/server/build/bundle.js:267024:12)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:272896:23)
      "code": "SQLITE_ERROR"
    }
2024-07-24T13:20:34.646Z [error]: /api/filler-lists 
    err: {
      "type": "SqliteError",
      "message": "ambiguous column name: program_uuid",
      "stack":
          SqliteError: ambiguous column name: program_uuid
              at Database.prepare (file:///tunarr/server/build/bundle.js:24711:26)
              at SqliteConnection.executeQuery (file:///tunarr/server/build/bundle.js:260844:27)
              at connection.executeQuery (file:///tunarr/server/build/bundle.js:258745:35)
              at file:///tunarr/server/build/bundle.js:253323:40
              at DefaultConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:258597:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async _DefaultQueryExecutor.executeQuery (file:///tunarr/server/build/bundle.js:253322:12)
              at async _SelectQueryBuilderImpl.execute (file:///tunarr/server/build/bundle.js:254762:21)
              at async FillerDB.getAllFillers (file:///tunarr/server/build/bundle.js:267024:12)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:272896:23)
      "code": "SQLITE_ERROR"
    }
2024-07-24T13:20:34.647Z [error]: undefined {"url":"/api/filler-lists"}
    error: {
      "code": "SQLITE_ERROR"
    }
```

**Comment by chrisbenincasa** [comment]
Thanks for the report - I'll take a look!
