### ISSUE TITLE
Crash when creating my first channel.

### ISSUE THREAD

**Issue by zypherion** [chrisbenincasa/tunarr#781]
### Contact Details

zxcbvnm90@gmail.com

### What happened?

I was trying to create my first channel and receiving an error "Error saving programs. Zodios: Invalid Body parameter 'body'". When I expanded the list of shows added and started to scroll through to make sure none of them looked weird, I met a friendly dog telling me everything was fine... But it was not fine.

I'll try to create the channel again, with less shows selected this time, and see how that goes.

### Version

0.10.3

### What browser did you experience the the problem on?

Chrome (128.0.0.0)

### What operating system are you using?

Windows (NT 10.0)

### Relevant log output

```shell
RangeError: Invalid time value
    at PXe (http://192.168.0.201:8000/web/assets/index-BXnYKyLJ.js:391:40605)
    at HM (http://192.168.0.201:8000/web/assets/index-BXnYKyLJ.js:56:19552)
    at BU (http://192.168.0.201:8000/web/assets/index-BXnYKyLJ.js:58:44104)
    at $U (http://192.168.0.201:8000/web/assets/index-BXnYKyLJ.js:58:39822)
    at hse (http://192.168.0.201:8000/web/assets/index-BXnYKyLJ.js:58:39748)
    at k1 (http://192.168.0.201:8000/web/assets/index-BXnYKyLJ.js:58:39598)
    at yI (http://192.168.0.201:8000/web/assets/index-BXnYKyLJ.js:58:35960)
    at OU (http://192.168.0.201:8000/web/assets/index-BXnYKyLJ.js:58:34907)
    at w (http://192.168.0.201:8000/web/assets/index-BXnYKyLJ.js:43:1550)
    at MessagePort.O (http://192.168.0.201:8000/web/assets/index-BXnYKyLJ.js:43:1914)
```

**Comment by chrisbenincasa** [comment]
Closing this out as stale. Let me know if this is still an issue and I can reopen and investigate.
