### ISSUE TITLE
Error 400 when saving programming

### ISSUE THREAD

**Issue by zolakk** [chrisbenincasa/tunarr#863]
I have a Plex collection of movies with 95 entries I want to add to programming but when trying to save I get "Error saving programs. Request failed with status code 400". I tried turning up the logging level in my docker compose from the default of INFO to both DEBUG and even TRACE but I don't see anything in the logs at all when clicking save. I've narrowed it down to one entry but I have no idea why it's problematic - there's no special characters or anything, shows the correct info when clicking the "i" button in the programming list and plays fine through Plex. I can do without no problem, but is there a way to find out what the problem is?

**Comment by chrisbenincasa** [comment]
Thanks for the report. Not sure why the logging isn't working. When i purposefully make a bad request, I get something like this on the server:

```
@tunarr/server:dev:     err: {
@tunarr/server:dev:       "type": "Error",
@tunarr/server:dev:       "message": "body/programs/1/duration Required",
@tunarr/server:dev:       "stack":
@tunarr/server:dev:           Error: body/programs/1/duration Required
@tunarr/server:dev:               at defaultSchemaErrorFormatter (/home/christian/Code/tunarr/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/context.js:93:10)
@tunarr/server:dev:               at wrapValidationError (/home/christian/Code/tunarr/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/validation.js:249:17)
@tunarr/server:dev:               at validate (/home/christian/Code/tunarr/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/validation.js:167:16)
@tunarr/server:dev:               at preValidationCallback (/home/christian/Code/tunarr/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/handleRequest.js:89:25)
@tunarr/server:dev:               at handler (/home/christian/Code/tunarr/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/handleRequest.js:73:7)
@tunarr/server:dev:               at /home/christian/Code/tunarr/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/contentTypeParser.js:212:9
@tunarr/server:dev:               at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
@tunarr/server:dev:               at done (/home/christian/Code/tunarr/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/contentTypeParser.js:205:14)
@tunarr/server:dev:               at Parser.defaultJsonParser [as fn] (/home/christian/Code/tunarr/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/contentTypeParser.js:315:5)
@tunarr/server:dev:               at IncomingMessage.onEnd (/home/christian/Code/tunarr/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/contentTypeParser.js:294:27)
@tunarr/server:dev:               at IncomingMessage.emit (node:events:518:28)
@tunarr/server:dev:               at IncomingMessage.emit (node:domain:488:12)
@tunarr/server:dev:               at endReadableNT (node:internal/streams/readable:1696:12)
@tunarr/server:dev:               at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
@tunarr/server:dev:       "statusCode": 400,
@tunarr/server:dev:       "code": "FST_ERR_VALIDATION",
@tunarr/server:dev:       "validation": [
@tunarr/server:dev:         {
@tunarr/server:dev:           "keyword": "invalid_type",
@tunarr/server:dev:           "instancePath": "/programs/1/duration",
@tunarr/server:dev:           "schemaPath": "#/programs/1/duration/invalid_type",
@tunarr/server:dev:           "params": {
@tunarr/server:dev:             "issue": {
@tunarr/server:dev:               "code": "invalid_type",
@tunarr/server:dev:               "expected": "number",
@tunarr/server:dev:               "received": "undefined",
@tunarr/server:dev:               "path": [
@tunarr/server:dev:                 "programs",
@tunarr/server:dev:                 1,
@tunarr/server:dev:                 "duration"
@tunarr/server:dev:               ],
@tunarr/server:dev:               "message": "Required"
@tunarr/server:dev:             }
@tunarr/server:dev:           },
@tunarr/server:dev:           "message": "Required"
@tunarr/server:dev:         }
@tunarr/server:dev:       ],
@tunarr/server:dev:       "validationContext": "body"
@tunarr/server:dev:     }
```

In any case, can you add the singular bad program, attempt to save, and then grab the failing request body that is sent to Tunarr via the browser dev tools and paste here? 

The 400 generally just means there is some field that Tunarr is expecting that is missing

**Comment by zolakk** [comment]
Weird, I must have been impatient or something because the logging appears to be working fine now after sitting for a while. Her's the error from the log:
```
2024-10-15T16:21:21.521Z [error]: POST /api/channels/:id/programming 
    err: {
      "type": "ZodError",
      "message": "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"number\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"programs\",\n      1,\n      \"originalProgram\",\n      \"program\",\n      \"addedAt\"\n    ],\n    \"message\": \"Required\"\n  }\n]",
      "stack":
          ZodError: [
            {
              "code": "invalid_type",
              "expected": "number",
              "received": "undefined",
              "path": [
                "programs",
                1,
                "originalProgram",
                "program",
0=a 1=d 2=d 3=e 4=d 5=A 6=t 
              ],
              "message": "Required"
            }
          ]
              at get error [as error] (file:///tunarr/server/build/bundle.js:231943:23)
              at _ZodDiscriminatedUnion.parse (file:///tunarr/server/build/bundle.js:232046:19)
              at file:///tunarr/server/build/bundle.js:218834:34
              at validateParam (file:///tunarr/server/build/bundle.js:181300:41)
              at validate (file:///tunarr/server/build/bundle.js:181331:22)
              at preValidationCallback (file:///tunarr/server/build/bundle.js:181537:29)
              at handler (file:///tunarr/server/build/bundle.js:181523:11)
              at file:///tunarr/server/build/bundle.js:196785:13
              at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
              at done (file:///tunarr/server/build/bundle.js:196778:18)
              at Parser3.defaultJsonParser [as fn] (file:///tunarr/server/build/bundle.js:196871:9)
              at IncomingMessage.onEnd (file:///tunarr/server/build/bundle.js:196850:33)
              at IncomingMessage.emit (node:events:519:28)
              at endReadableNT (node:internal/streams/readable:1696:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      "aggregateErrors": [
        {
          "type": "Object",
          "message": "Required",
          "stack":
              
          "code": "invalid_type",
          "expected": "number",
          "received": "undefined",
          "path": [
            "programs",
            1,
            "originalProgram",
            "program",
0=a 1=d 2=d 3=e 4=d 5=A 6=t 
          ]
        }
      ],
      "issues": [
        {
          "code": "invalid_type",
          "expected": "number",
          "received": "undefined",
          "path": [
            "programs",
            1,
            "originalProgram",
            "program",
0=a 1=d 2=d 3=e 4=d 5=A 6=t 
          ],
          "message": "Required"
        }
      ],
      "name": "ZodError",
      "statusCode": 400,
      "code": "FST_ERR_VALIDATION",
      "validationContext": "body"
    }

```

and here's the body for that one:
```
{
    "type": "manual",
    "lineup": [
        {
            "duration": 5620128,
            "index": 0
        }
    ],
    "programs": [
        {
            "id": "plex|Home Plex NAS|35942",
            "persisted": false,
            "originalProgram": {
                "sourceType": "plex",
                "program": {
                    "ratingKey": "35942",
                    "key": "/library/metadata/35942",
                    "guid": "plex://movie/5d77685be870fd001f19e78c",
                    "slug": "bloody-new-year",
                    "studio": "Lazer Entertainment",
                    "type": "movie",
                    "title": "Bloody New Year",
                    "librarySectionTitle": "Movies",
                    "librarySectionID": 5,
                    "librarySectionKey": "/library/sections/5",
                    "contentRating": "R",
                    "summary": "Six shipwrecked English teenagers take refuge in an island hotel that is decorated for New Years. The problem is, it's early summer, and soon enough, even the walls themselves are striking out against them…",
                    "audienceRating": 2.4,
                    "year": 1987,
                    "tagline": "Should old acquaintance be forgot? Or just brutally murdered.",
                    "thumb": "/library/metadata/35942/thumb/1727481847",
                    "art": "/library/metadata/35942/art/1727481847",
                    "duration": 5620128,
                    "originallyAvailableAt": "1987-05-11",
                    "updatedAt": 1727481847,
                    "audienceRatingImage": "rottentomatoes://image.rating.spilled",
                    "chapterSource": "media",
                    "Media": [
                        {
                            "id": 38036,
                            "duration": 5620128,
                            "bitrate": 11235,
                            "width": 1920,
                            "height": 1040,
                            "aspectRatio": 1.85,
                            "audioChannels": 2,
                            "audioCodec": "ac3",
                            "videoCodec": "hevc",
                            "videoResolution": "1080",
                            "container": "mkv",
                            "videoFrameRate": "24p",
                            "videoProfile": "main 10",
                            "hasVoiceActivity": false,
                            "Part": [
                                {
                                    "id": 78121,
                                    "key": "/library/parts/78121/0/file.mkv",
                                    "duration": 5620128,
                                    "file": "/share/Plex/Media/Movies/Bloody New Year (1987)/Bloody New Year (1987).mkv",
                                    "size": 7894977766,
                                    "container": "mkv",
                                    "videoProfile": "main 10"
                                }
                            ]
                        }
                    ],
                    "Image": [
                        {
                            "alt": "Bloody New Year",
                            "type": "coverPoster",
                            "url": "/library/metadata/35942/thumb/1727481847"
                        },
                        {
                            "alt": "Bloody New Year",
                            "type": "background",
                            "url": "/library/metadata/35942/art/1727481847"
                        },
                        {
                            "alt": "Bloody New Year",
                            "type": "clearLogo",
                            "url": "/library/metadata/35942/clearLogo/1727481847"
                        }
                    ],
                    "UltraBlurColors": {
                        "topLeft": "4e1a17",
                        "topRight": "af1203",
                        "bottomRight": "903d46",
                        "bottomLeft": "af1304"
                    },
                    "Genre": [
                        {
                            "tag": "Horror"
                        },
                        {
                            "tag": "Mystery"
                        }
                    ],
                    "Country": [
                        {
                            "tag": "United Kingdom"
                        }
                    ],
                    "Collection": [
                        {
                            "tag": "Halloween Movies"
                        }
                    ],
                    "Director": [
                        {
                            "tag": "Norman J. Warren"
                        }
                    ],
                    "Writer": [
                        {
                            "tag": "Norman J. Warren"
                        },
                        {
                            "tag": "Hayden Pearce"
                        }
                    ],
                    "Role": [
                        {
                            "tag": "Suzy Aitchison"
                        },
                        {
                            "tag": "Nikki Brooks"
                        },
                        {
                            "tag": "Colin Heywood"
                        }
                    ],
                    "serverName": "Home Plex NAS",
                    "serverId": "7ddda31f-0ecc-4232-87e1-ef0a7aaa9fce"
                }
            },
            "duration": 5620128,
            "externalSourceName": "Home Plex NAS",
            "externalSourceType": "plex",
            "externalKey": "35942",
            "uniqueId": "plex|Home Plex NAS|35942",
            "type": "content",
            "subtype": "movie",
            "summary": "Six shipwrecked English teenagers take refuge in an island hotel that is decorated for New Years. The problem is, it's early summer, and soon enough, even the walls themselves are striking out against them…",
            "title": "Bloody New Year",
            "externalIds": [
                {
                    "type": "multi",
                    "source": "plex",
                    "sourceId": "Home Plex NAS",
                    "id": "35942"
                }
            ],
            "originalIndex": 0,
            "startTimeOffset": 0
        }
    ]
}


```

so if I read the error and body correctly, it seems this one is missing a value for "addedAt". Any idea how to fix that? I assume it's something from the Plex side but given the name I would think it should be an auto generated value

**Comment by zolakk** [comment]
It looks like Plex does indeed have the addedAt value, so I'm not sure where the break down might be. Here's the XML from the Plex side for that part

```
<Related>
<Hub hubKey="/library/metadata/38639" key="/library/sections/5/all?type=1&tagId=241714&sort=originallyAvailableAt,year:nullsLast" title="Halloween Movies Collection" type="movie" hubIdentifier="collection.related.5.1" context="hub.collection.related" size="1" more="1" style="shelf">
<Video ratingKey="38639" key="/library/metadata/38639" guid="plex://movie/5f40c1e9c63b480040f5ef2b" slug="the-visit-71" studio="K-58 Films" type="movie" title="The Visit" titleSort="Visit" summary="A dying woman gets a ghostly visit." audienceRating="9.0" tagline="A dying woman gets a ghostly visit." thumb="/library/metadata/38639/thumb/1727518366" art="/library/metadata/38639/art/1727518366" duration="5641856" addedAt="1456642538" updatedAt="1727518366" audienceRatingImage="imdb://image.rating" chapterSource="media">
```

**Comment by chrisbenincasa** [comment]
Awesome, thanks for the details. Interesting that the JSON from Plex is missing addedAt but the XML has it. In any case, Tunarr doesn't require it, so I'll just mark it optional.
