### ISSUE TITLE
Tunarr guide get reset on plex live tv config

### ISSUE THREAD

**Issue by xenovia** [chrisbenincasa/tunarr#879]
I'm having an issue where by the guide configuration on plex live tv dvr become empty after a few hours i dont know why and i cant see the issue

Unraid : 6.12.13
docker Version : ghcr.io/chrisbenincasa/tunarr:latest-nvidia

![image](https://github.com/user-attachments/assets/3734b49b-2153-4cb6-bbcb-76220f7c91a0)

If i try to run  the channel i get that after populating the guide,

```
[out#0/nut @ 0x3232680] Starting thread...
2024-10-15T21:55:04.305Z [error]: Error playing video {"code":8,"cmd":"/usr/bin/ffmpeg -hide_banner -threads 8 -fflags +genpts+discardcorrupt+igndts -loglevel verbose -reconnect 1 -reconnect_on_network_error 1 -reconnect_streamed 1 -multiple_requests 1 -readrate 1.0 -readrate_initial_burst 45 -ss 5556.727 -i http://10.0.0.22:32400/library/parts/227017/1701883809/file.mkv?X-Plex-Token=REDACTED -i http://localhost:8000/images/tunarr.png -filter_complex [0:0]null[video];[video]scale=720:360:flags=bicubic,format=yuv420p[scaled];[scaled]pad=720:480:(ow-iw)/2:(oh-ih)/2[blackpadded];[blackpadded]setsar=1,format=yuv420p[siz];[1:v]scale=72:-1[icn];[siz][icn]overlay=x=W-w-7:y=H-h-5[comb];[0:1]anull[audio];[audio]aresample=48000,aresample=async=1:first_pts=0,apad=whole_dur=2218153ms[padded] -map [comb] -c:v libx265 -b:v 10000k -maxrate:v 10000k -bufsize:v 1000k -sc_threshold 0 -video_track_timescale 90000 -map [padded] -flags cgop+ilme -b:a 192k -maxrate:a 192k -bufsize:a 50k -ac 2 -ar 48k -map_metadata -1 -movflags +faststart -muxdelay 0 -muxpreload 0 -fps_mode cfr -metadata service_provider=\"tunarr\" -metadata service_name=\"Halloween\" -t 2218153ms -g 96 -keyint_min 96 -force_key_frames expr:gte(t,n_forced*2) -f hls -hls_time 4 -hls_list_size 0 -segment_list_flags +live -hls_flags program_date_time+omit_endlist+discont_start+append_list -hls_segment_type mpegts -hls_base_url /stream/channels/be1491ef-8591-4d5a-a0a9-2274826e2b08/hls/ -hls_segment_filename streams/stream_be1491ef-8591-4d5a-a0a9-2274826e2b08/data%05d.ts -master_pl_name master.m3u8 streams/stream_be1491ef-8591-4d5a-a0a9-2274826e2b08/stream.m3u8"}
2024-10-15T21:55:04.312Z [info]: Concat Wrapper FFMPEG exited. (signal=null, code=0, expected?=true) {"args":"-nostdin -threads 1 -hide_banner -loglevel verbose -user_agent Ffmpeg Tunarr/0.12.5 -nostats -fflags +genpts+discardcorrupt+igndts -reconnect 1 -reconnect_at_eof 1 -readrate 1 -i http://localhost:8000/stream/channels/be1491ef-8591-4d5a-a0a9-2274826e2b08.m3u8?mode=hls -map 0 -c copy -f mpegts pipe:1"}
2024-10-15T21:55:05.249Z [error]: Bailing on stream start, had error! {"sessionId":"35867cb1-c4b7-4ab0-b09c-c96854683725","channel":"be1491ef-8591-4d5a-a0a9-2274826e2b08","sessionType":"hls"}
    err: {
      "type": "Error",
      "message": "Error in underlying FFMPEG process: (code=8)",
      "stack":
          Error: Error in underlying FFMPEG process: (code=8)
              at _FfmpegTranscodeSession.<anonymous> (file:///tunarr/server/build/bundle.js:272587:24)
              at _FfmpegTranscodeSession.emit (node:events:531:35)
              at _FfmpegProcess.<anonymous> (file:///tunarr/server/build/bundle.js:269551:12)
              at _FfmpegProcess.emit (node:events:531:35)
              at ChildProcess.<anonymous> (file:///tunarr/server/build/bundle.js:269489:14)
              at ChildProcess.emit (node:events:519:28)
              at ChildProcess._handle.onexit (node:internal/child_process:294:12)
              at Process.callbackTrampoline (node:internal/async_hooks:130:17)
    }
2024-10-15T21:55:05.250Z [error]: Error starting stream after retrying {"sessionId":"35867cb1-c4b7-4ab0-b09c-c96854683725","channel":"be1491ef-8591-4d5a-a0a9-2274826e2b08","sessionType":"hls"}
    err: {
      "type": "Error",
      "message": "Error in underlying FFMPEG process: (code=8)",
      "stack":
          Error: Error in underlying FFMPEG process: (code=8)
              at _FfmpegTranscodeSession.<anonymous> (file:///tunarr/server/build/bundle.js:272587:24)
              at _FfmpegTranscodeSession.emit (node:events:531:35)
              at _FfmpegProcess.<anonymous> (file:///tunarr/server/build/bundle.js:269551:12)
              at _FfmpegProcess.emit (node:events:531:35)
              at ChildProcess.<anonymous> (file:///tunarr/server/build/bundle.js:269489:14)
              at ChildProcess.emit (node:events:519:28)
              at ChildProcess._handle.onexit (node:internal/child_process:294:12)
              at Process.callbackTrampoline (node:internal/async_hooks:130:17)
    }
2024-10-15T21:55:05.250Z [error]: Received error from session. Shutting down {"sessionType":"hls","channelId":"be1491ef-8591-4d5a-a0a9-2274826e2b08"}
    error: {}
```

**Comment by chrisbenincasa** [comment]
i have actually been experiencing a similar problem but haven't gotten down a solid reproduction yet. I tracked my thoughts here: https://github.com/chrisbenincasa/tunarr/issues/818

**Comment by chrisbenincasa** [comment]
This also happens to me when I have "send channel updates" disabled in my plex server settings in tunarr too

**Comment by chrisbenincasa** [comment]
Regarding the stream error - that is a separate bug. You'll need to turn on ffmpeg logging in the Tunarr settings and provide those logs so we can look into it further

**Comment by xenovia** [comment]
> This also happens to me when I have "send channel updates" disabled in my plex server settings in tunarr too

Alright i will do another ticket then for this one

**Comment by chrisbenincasa** [comment]
I just had a thought here - do you have dizqueTV running still? And if so, do you have these options enabled for your Plex server?

<img width="221" alt="Screenshot 2024-10-23 at 7 34 54 AM" src="https://github.com/user-attachments/assets/8cd4e6c1-cb61-4f0c-a2a2-dedd867837d5">

I had these enabled and I think that DTV was periodically overwriting my Tunarr channel mappings in Plex

**Comment by xenovia** [comment]
Hi no i dont anymore

**Comment by chrisbenincasa** [comment]
OK. Do you have the auto-update enabled from Tunarr then?

**Comment by xenovia** [comment]
> OK. Do you have the auto-update enabled from Tunarr then?

on unraid yes but inside the docker not sure where it should be can you guide me ?

**Comment by chrisbenincasa** [comment]
Yes - go to Settings > Sources > click on the pencil for your server
<img width="1057" alt="Screenshot 2024-10-24 at 9 56 12 PM" src="https://github.com/user-attachments/assets/451525c1-4db8-4628-948d-4ed8e0f76eb5">

We're lookingn at "auto guide update" here. 

In any case, I think I fixed this in https://github.com/chrisbenincasa/tunarr/commit/70ecd0035bc322f9b700dc8f3f7076a0cac533a7, so you can try upgrading to 0.14.2 and see if it helps. I haven't had my channels lose mapping in a while

**Comment by xenovia** [comment]
i got bot options checked and latest update  for nvidia it seem working now.

thx

**Comment by chrisbenincasa** [comment]
Awesome!
