### ISSUE TITLE
Apparent time zone issues when creating time slots

### ISSUE THREAD

**Issue by pavlov70** [chrisbenincasa/tunarr#944]
I'm still experiencing unexpected behavior with time slots and I think it's time zone related. I'm in EST time zone and last week I was unable to create a time slot starting at 8pm or later (-4 hours GMT). On Sunday our time moved back 1 hour (EDT to EST) and I am now unable to create a timer starting at 7pm or later (-5 hours GMT). Additionally, the guide shows unexpected times. Programming I expect to  see start at 6pm starts at 1pm.

Below is the last part of the log when I attempted to save a time slot for 8pm. Kindly let me know if you would like the database or more details.

2024-11-08T03:12:34.515Z [warn]: End time exceeds what the current cached guide generation (requested: 2024-11-09T05:00:00+00:00, end: 2024-11-09T03:06:26+00:00)
2024-11-08T03:12:34.515Z [warn]: End time exceeds what the current cached guide generation (requested: 2024-11-09T05:00:00+00:00, end: 2024-11-09T03:06:26+00:00)
2024-11-08T03:12:55.869Z [warn]: End time exceeds what the current cached guide generation (requested: 2024-11-09T04:00:00+00:00, end: 2024-11-09T03:06:26+00:00)
2024-11-08T03:12:55.870Z [warn]: End time exceeds what the current cached guide generation (requested: 2024-11-09T04:00:00+00:00, end: 2024-11-09T03:06:26+00:00)
2024-11-08T03:12:55.871Z [warn]: End time exceeds what the current cached guide generation (requested: 2024-11-09T04:00:00+00:00, end: 2024-11-09T03:06:26+00:00)
2024-11-08T03:12:55.872Z [warn]: End time exceeds what the current cached guide generation (requested: 2024-11-09T04:00:00+00:00, end: 2024-11-09T03:06:26+00:00)
2024-11-08T03:12:55.872Z [warn]: End time exceeds what the current cached guide generation (requested: 2024-11-09T04:00:00+00:00, end: 2024-11-09T03:06:26+00:00)
2024-11-08T03:12:55.873Z [warn]: End time exceeds what the current cached guide generation (requested: 2024-11-09T04:00:00+00:00, end: 2024-11-09T03:06:26+00:00)
2024-11-08T03:12:55.873Z [warn]: End time exceeds what the current cached guide generation (requested: 2024-11-09T04:00:00+00:00, end: 2024-11-09T03:06:26+00:00)
2024-11-08T03:12:55.873Z [warn]: End time exceeds what the current cached guide generation (requested: 2024-11-09T04:00:00+00:00, end: 2024-11-09T03:06:26+00:00)
2024-11-08T03:15:53.562Z [error]: /api/channels/:id/programming 
    err: {
      "type": "Error",
      "message": "Could not find a suitable slot",
      "stack":
          Error: Could not find a suitable slot
              at scheduleTimeSlots (file:///tunarr/server/build/bundle.js:171072:13)
              at ChannelDB.updateLineup (file:///tunarr/server/build/bundle.js:187236:67)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:188493:22)
    }
2024-11-08T03:15:53.563Z [error]: undefined {"url":"/api/channels/:id/programming"}
    error: {}
2024-11-08T03:15:53.564Z [error]: POST /api/channels/:id/programming 
    err: {
      "type": "Error",
      "message": "Could not find a suitable slot",
      "stack":
          Error: Could not find a suitable slot
              at scheduleTimeSlots (file:///tunarr/server/build/bundle.js:171072:13)
              at ChannelDB.updateLineup (file:///tunarr/server/build/bundle.js:187236:67)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:188493:22)
    }

**Comment by pavlov70** [comment]
I just validated the local time on the server and it is correct. So I don't think it's that.

xxxxx@plex:~/bin/tunarr/logs$ date
Thu Nov  7 10:26:07 PM EST 2024

**Comment by chrisbenincasa** [comment]
Interesting... I am in the same timezone, but cannot reproduce the issue. I successfully created a schedule with: 

<img width="263" alt="Screenshot 2024-11-07 at 10 56 02 PM" src="https://github.com/user-attachments/assets/f8345d44-af45-4be4-94f9-6adbc34ea245">

So there is definitely something else strange happening... I think there are probably a fair amount of timezone issues throughout the app, tbh. time slot scheduling is one of the only places where TZ is consulted... 

Do you have a minimal schedule you can get the error message with?

**Comment by pavlov70** [comment]
Sure can. Here's my guide for the test channel. Note how it starts at 12:55pm despite my time slot of 5:55pm:

![image](https://github.com/user-attachments/assets/0c6d3056-49d3-4db7-a713-676e89e64c64)

![image](https://github.com/user-attachments/assets/f8bc5147-feb2-4b12-be1e-c99c28768850)
 And here's the log. I deleted it before I restarted the container. I made a couple of attempts to change the time to later than 6:55pm and then changed it to 5:55 as you see above.

`2024-11-08T04:14:00.796Z [info]: Using Tunarr database directory: /config/tunarr
2024-11-08T04:14:00.977Z [info]: Searching for legacy dizquetv directory at /.dizquetv
2024-11-08T04:14:00.978Z [info]: Found legacy dizquetv database folder, but not migrating because an existing Tunarr database was also found
2024-11-08T04:14:02.059Z [info]: XMLTV Updated at 11/8/2024, 4:14:02 AM
2024-11-08T04:14:02.076Z [info]: HTTP server listening on host:port: http://0.0.0.0:8000
2024-11-08T04:14:06.022Z [info]: Writing backup to /config/tunarr/backups/tunarr-backup-20241108_041406.tar
2024-11-08T04:14:06.695Z [info]: Successfully generated backup to /config/tunarr/backups/tunarr-backup-20241108_041406.tar
2024-11-08T04:15:09.664Z [error]: /api/channels/:id/programming 
    err: {
      "type": "Error",
      "message": "Could not find a suitable slot",
      "stack":
          Error: Could not find a suitable slot
              at scheduleTimeSlots (file:///tunarr/server/build/bundle.js:171072:13)
              at ChannelDB.updateLineup (file:///tunarr/server/build/bundle.js:187236:67)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:188493:22)
    }
2024-11-08T04:15:09.666Z [error]: undefined {"url":"/api/channels/:id/programming"}
    error: {}
2024-11-08T04:15:09.666Z [error]: POST /api/channels/:id/programming 
    err: {
      "type": "Error",
      "message": "Could not find a suitable slot",
      "stack":
          Error: Could not find a suitable slot
              at scheduleTimeSlots (file:///tunarr/server/build/bundle.js:171072:13)
              at ChannelDB.updateLineup (file:///tunarr/server/build/bundle.js:187236:67)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:188493:22)
    }
2024-11-08T04:16:33.761Z [info]: XMLTV Updated at 11/8/2024, 4:16:33 AM
`

**Comment by chrisbenincasa** [comment]
Ok, great. So I haven't been able to get the error on my end, but I do see the timezome discrepancy between slots and the guide page.

**Comment by chrisbenincasa** [comment]
More interestingly, I cannot even reproduce the discrepancy on my local machine (i.e. when server is on the same machine as my browser)

**Comment by chrisbenincasa** [comment]
Sorry for the comment spam - but here is a "fix" for that issue, at least on my end. Have to set the `TZ` environment variable on the container. I will update the docs to reflect this

**Comment by pavlov70** [comment]
No worries and thanks! I can confirm updating the timezone in the container solved the issue.

**Comment by chrisbenincasa** [comment]
Great! I updated the docs.
