### ISSUE TITLE
Query error: 'select from "program_external_id" where "uuid" = ?'

### ISSUE THREAD

**Issue by Rohja** [chrisbenincasa/tunarr#958]
Hi,

I'm encountering this issue (that seems to also break the playback from Jellyfin). Not sure what's the cause.
I'm available if you need me to try some reproduction steps.

```
2024-11-10T19:51:55.495Z [error]: Query error: 'select from "program_external_id" where "uuid" = ?'
["2bc3fdb5-cc0f-481c-94d9-07c6223f0651"] 
    err: {
      "type": "SqliteError",
      "message": "near \"from\": syntax error",
      "stack":
          SqliteError: near "from": syntax error
              at Database.prepare (file:///tunarr/server/build/bundle.js:20338:26)
              at SqliteConnection.executeQuery (file:///tunarr/server/build/bundle.js:167207:27)
              at connection.executeQuery (file:///tunarr/server/build/bundle.js:165240:35)
              at file:///tunarr/server/build/bundle.js:158234:39
              at DefaultConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:165092:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async _DefaultQueryExecutor.executeQuery (file:///tunarr/server/build/bundle.js:158233:12)
              at async _SelectQueryBuilderImpl.execute (file:///tunarr/server/build/bundle.js:159759:20)
              at async _SelectQueryBuilderImpl.executeTakeFirst (file:///tunarr/server/build/bundle.js:159763:22)
              at async _SelectQueryBuilderImpl.executeTakeFirstOrThrow (file:///tunarr/server/build/bundle.js:159767:20)
              at async ProgramDB.updateProgramPlexRatingKey (file:///tunarr/server/build/bundle.js:176722:14)
      "code": "SQLITE_ERROR"
    }
2024-11-10T19:51:55.500Z [error]: Error while updating Jellyfin file path for program 5bc48cab-1262-44a0-88cd-06e3079e0bbc {"jellyfinServer":"Coredata"}
    err: {
      "type": "SqliteError",
      "message": "near \"from\": syntax error",
      "stack":
          SqliteError: near "from": syntax error
              at Database.prepare (file:///tunarr/server/build/bundle.js:20338:26)
              at SqliteConnection.executeQuery (file:///tunarr/server/build/bundle.js:167207:27)
              at connection.executeQuery (file:///tunarr/server/build/bundle.js:165240:35)
              at file:///tunarr/server/build/bundle.js:158234:39
              at DefaultConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:165092:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async _DefaultQueryExecutor.executeQuery (file:///tunarr/server/build/bundle.js:158233:12)
              at async _SelectQueryBuilderImpl.execute (file:///tunarr/server/build/bundle.js:159759:20)
              at async _SelectQueryBuilderImpl.executeTakeFirst (file:///tunarr/server/build/bundle.js:159763:22)
              at async _SelectQueryBuilderImpl.executeTakeFirstOrThrow (file:///tunarr/server/build/bundle.js:159767:20)
              at async ProgramDB.updateProgramPlexRatingKey (file:///tunarr/server/build/bundle.js:176722:14)
      "code": "SQLITE_ERROR"
    }
```

I can see it happened to some others IDs too like (_62c20d57-56ad-4f90-9ae9-1978b97a8416_). 

Running in Docker with `ghcr.io/chrisbenincasa/tunarr:latest-nvidia`.

**Comment by chrisbenincasa** [comment]
Hey thanks for the report! I’ll see if I can find where the bad query is
generated, should be straightforward

**Comment by chrisbenincasa** [comment]
This actually should be resolved with https://github.com/chrisbenincasa/tunarr/pull/933 which was released recently (not sure when you last pulled). The new code doesn't hit the query on this path (and the underlying query error should be fixed too)

**Comment by chrisbenincasa** [comment]
@Rohja - let me know the exact Tunarr version (at the bottom of the left drawer) and we'll know whether it's solved by the PR i linked or a new issue

**Comment by Rohja** [comment]
Hi, thanks for your quick answer. 

This is what I was running at the time of the issue:

```
Version: 0.15.2
FFMPEG: 7.0
NodeJS: 20.18.0
```

I just updated my container. I'll let you know if the issue is still occuring.

**Comment by Rohja** [comment]
Pulling the latest version fixed the issues, thanks ! :)

**Comment by chrisbenincasa** [comment]
Great!
